# Generated by Django 4.1.1 on 2022-09-23 06:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='image'),
        ),
    ]
